### PR TITLE
Developer friendly

### PR DESCRIPTION
**Pull request by graypegg**
Just adds a couple things to make this plugin a little easier to work on/implement for developers. The following was added
- A preloader animation
- Captions
- Use of HTML5 tags (figure instead of div)
- More options when calling h5lightbox()
- Error information

### CODE REVIEW

**Comment by morganestes** [comment]
@toish Thanks for the PR. I'll take a look and get back to you soon.

**Comment by toish** [comment]
Any chance of this getting merged?

**Comment by morganestes** [comment]
@toish I'm sorry, I've really let this slip. I don't have a timetable for getting it reviewed other than by the end of the year.

I appreciate your patience and contribution, and hope to see it included in the next release.

**Comment by toish** [comment]
553a98434aa21808310057d3

**Comment by toish** [comment]
Gonna just close this, looking over the pull request now; it's pretty terrible, made when I was still learning JS.

**Pull request closed without merging**
